const players=[
{name:"Josh Allen",pos:"QB",age:30,team:"BUF",value:98,trend:"↑"}, {name:"Lamar Jackson",pos:"QB",age:29,team:"BAL",value:96,trend:"↑"},
{name:"Jahmyr Gibbs",pos:"RB",age:24,team:"DET",value:95,trend:"↑"}, {name:"Bijan Robinson",pos:"RB",age:24,team:"ATL",value:94,trend:"↑"},
{name:"Ja'Marr Chase",pos:"WR",age:26,team:"CIN",value:99,trend:"→"}, {name:"Justin Jefferson",pos:"WR",age:27,team:"MIN",value:97,trend:"→"},
{name:"Jaxon Smith-Njigba",pos:"WR",age:24,team:"SEA",value:93,trend:"↑"}, {name:"Amon-Ra St. Brown",pos:"WR",age:26,team:"DET",value:92,trend:"→"},
{name:"Brock Bowers",pos:"TE",age:25,team:"LV",value:95,trend:"↑"}, {name:"Trey McBride",pos:"TE",age:26,team:"ARI",value:94,trend:"↑"},
{name:"Malik Willis",pos:"QB",age:27,team:"GB",value:64,trend:"↑"}, {name:"Terry McLaurin",pos:"WR",age:31,team:"WAS",value:60,trend:"↓"},
{name:"Jonathan Taylor",pos:"RB",age:27,team:"IND",value:82,trend:"→"}, {name:"Deebo Samuel",pos:"WR",age:30,team:"WAS",value:58,trend:"↓"},
{name:"AJ Barner",pos:"TE",age:24,team:"SEA",value:31,trend:"↑"}, {name:"Colby Parkinson",pos:"TE",age:27,team:"LAR",value:25,trend:"→"}
];
const roster=[["QB","Lamar Jackson",96],["RB","Jonathan Taylor",82],["RB","Jahmyr Gibbs",95],["WR","Jaxon Smith-Njigba",93],["WR","Terry McLaurin",60],["TE","AJ Barner",31],["FLEX","Amon-Ra St. Brown",92],["FLEX","Deebo Samuel",58]];
const league=[["1","Gridiron Kings","Marcus","A+","881","Elite"],["2","Thomas Dynasty","Tayden","A−","842","Contender"],["3","Fourth & Goal","Ryan","A−","829","Contender"],["4","Sunday Scaries","Jake","B+","806","Contender"],["5","The Rebuilders","Nick","B+","774","Rising"],["6","No Punt Intended","Chris","B","751","Playoffs"],["7","Waiver Wire","Dylan","B","735","Bubble"],["8","Goal Line Stand","Mike","B−","716","Bubble"],["9","The Taxmen","Alex","C+","690","Rebuild"],["10","Knee Deep","Sam","C+","674","Rebuild"],["11","Red Zone","Ben","C","641","Rebuild"],["12","Fourth Down","Josh","C−","612","Rebuild"]];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function initials(n){return n.split(" ").map(x=>x[0]).join("").slice(0,2)}
function renderGrades(){const data=[["QB",95],["RB",78],["WR",92],["TE",61],["DEPTH",72]];$("#grades").innerHTML=data.map(x=>`<div class="grade-row"><label>${x[0]}</label><div class="bar"><i style="width:${x[1]}%"></i></div><div class="grade">${x[1]}</div></div>`).join("")}
function renderWatch(){const list=players.filter(p=>["Malik Willis","Jaxon Smith-Njigba","Jonathan Taylor","AJ Barner"].includes(p.name));$("#watchlist").innerHTML=list.map(p=>`<div class="player-row"><div class="player-avatar">${initials(p.name)}</div><div class="player-name"><strong>${p.name}</strong><small>${p.pos} • ${p.team}</small></div><div class="value">${p.value}</div></div>`).join("")}
function renderRoster(){ $("#roster").innerHTML=roster.map((r,i)=>`<div class="roster-row"><div class="player-avatar">${r[0]}</div><div class="player-name"><strong>${r[1]}</strong><small>${r[0]} • Starter</small></div><div class="value">${r[2]}</div><div class="muted">P${i+1}</div></div>`).join("")}
function renderPicks(){let picks=[["2026","1.10","186"],["2027","1st","205"],["2027","2nd","94"],["2028","1st","192"]];$("#picks").innerHTML=picks.map(p=>`<div class="pick-row"><strong>${p[0]}</strong><div class="player-name"><strong>${p[1]}</strong><small>Draft pick</small></div><div class="value">${p[2]}</div></div>`).join("")}
function renderPlayers(){let q=$("#playerSearch").value.toLowerCase(),pos=$("#posFilter").value,age=$("#ageFilter").value;let filtered=players.filter(p=>(p.name.toLowerCase().includes(q)||p.team.toLowerCase().includes(q))&&(pos==="ALL"||p.pos===pos)&&(age==="ALL"||(age==="YOUNG"&&p.age<=25)||(age==="PRIME"&&p.age>=26&&p.age<=29)||(age==="VET"&&p.age>=30)));$("#playersTable").innerHTML=filtered.map((p,i)=>`<tr><td>${i+1}</td><td><strong>${p.name}</strong></td><td>${p.pos}</td><td>${p.age}</td><td>${p.team}</td><td><strong>${p.value}</strong></td><td class="${p.trend==="↓"?"":"trend-up"}">${p.trend}</td></tr>`).join("")}
function renderDraft(){let names=["Emmett Johnson","Kaytron Allen","Harold Fannin Jr.","Jeremiyah Love","Singleton","Jamari Taylor"];$("#draftBoard").innerHTML=["Gridiron Kings","Fourth & Goal","Sunday Scaries","No Punt Intended","The Rebuilders","Goal Line Stand","Waiver Wire","The Taxmen","Knee Deep","Thomas Dynasty"].map((n,i)=>`<div class="draft-pick"><div class="pick-num">${i+1}.0${i+1}</div><div><strong>${n}</strong><small class="muted"> Pick</small></div><div class="muted">${i===9?"ON CLOCK":"Complete"}</div></div>`).join("");$("#available").innerHTML=names.map((n,i)=>`<div class="available-row"><div class="rank">${i+1}</div><div><strong>${n}</strong><small class="muted"> Rookie • ${["RB","RB","TE","RB","RB","RB"][i]}</small></div><div class="value">${88-i*5}</div></div>`).join("")}
function renderLeague(){$("#leagueTable").innerHTML=league.map(r=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td><td>${r[2]}</td><td><strong>${r[3]}</strong></td><td>${r[4]}</td><td class="muted">${r[5]}</td></tr>`).join("")}
let trade={your:[],their:[]};
function renderTrade(){["your","their"].forEach(side=>{$("#"+side+"Trade").innerHTML=trade[side].length?trade[side].map((p,i)=>`<div class="trade-asset"><span><strong>${p.name}</strong> <small class="muted">${p.pos}</small></span><span><b>${p.value}</b> <button class="remove" onclick="removeTrade('${side}',${i})">×</button></span></div>`).join(""):`<p class="muted">No assets added yet.</p>`;$("#"+side+"Value").textContent=trade[side].reduce((a,p)=>a+p.value,0)});let a=trade.your.reduce((x,p)=>x+p.value,0),b=trade.their.reduce((x,p)=>x+p.value,0);if(a||b){let diff=a-b;if(Math.abs(diff)<6){$("#verdict").innerHTML='<p class="eyebrow">TRADE VERDICT</p><h2>Fair Trade</h2><p>Values are within a close range. Context and roster needs should decide it.</p>'}else{$("#verdict").innerHTML=`<p class="eyebrow">TRADE VERDICT</p><h2>${diff>0?"Your side wins":"Their side wins"} ${Math.abs(diff)} points</h2><p>${diff>0?"You are receiving more dynasty value.":"You are giving up more dynasty value."}</p>`}}}
function addTrade(side){let choices=players.filter(p=>!trade.your.includes(p)&&!trade.their.includes(p));if(!choices.length)return;let p=choices[Math.floor(Math.random()*choices.length)];trade[side].push(p);renderTrade();toast(`Added ${p.name} to ${side==="your"?"your":"their"} side`)}
function removeTrade(side,i){trade[side].splice(i,1);renderTrade()}
function toast(msg){let t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function showPage(page){$$(".page").forEach(x=>x.classList.remove("active-page"));$("#"+page).classList.add("active-page");$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===page));let titles={dashboard:"Dynasty Dashboard",team:"My Team",players:"Dynasty Rankings",trade:"Trade Analyzer",draft:"Draft Room",league:"League"};$("#pageTitle").textContent=titles[page];if(innerWidth<700)$(".sidebar").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"})}
$$(".nav-item").forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$("[data-goto]").forEach(b=>b.onclick=()=>showPage(b.dataset.goto));$$(".add-btn").forEach(b=>b.onclick=()=>addTrade(b.dataset.side));$("#playerSearch").oninput=renderPlayers;$("#posFilter").onchange=renderPlayers;$("#ageFilter").onchange=renderPlayers;$("#themeBtn").onclick=()=>{document.body.classList.toggle("light");localStorage.theme=document.body.classList.contains("light")?"light":"dark"};$("#mobileMenu").onclick=()=>$(".sidebar").classList.toggle("open");if(localStorage.theme==="light")document.body.classList.add("light");
renderGrades();renderWatch();renderRoster();renderPicks();renderPlayers();renderDraft();renderLeague();renderTrade();